### ISSUE TITLE
Build fails when calling `.withValetCertificates()` with no arguments

### ISSUE THREAD

**Issue by bakerkretzmar** [innocenzi/laravel-vite#136]
Adding `.withValetCertificates()` exactly like that, with no arguments, causes builds to fail.

Passing an empty object works fine: `.withValetCertificates({})`. I'm not very familiar with TypeScript but it looks like you just need an additional method definition with no arguments, kind of like the `.withCertificates()` method. I'll open a PR for that tomorrow morning unless someone beats me to it.

Reproduction repo (not much to see though): https://github.com/bakerkretzmar/laravel-vite-valet-cert-arguments-bug.

Steps to reproduce:

- fresh Laravel app install
- Valet linked and certificates created
- ran `npx apply laravel:vite`
- added the `.withValetCertificates()` method

Output of `npm run dev`:

```

> dev
> vite

failed to load config from /Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/vite.config.ts
error when starting dev server:
TypeError: Cannot destructure property 'domain' of 'undefined' as it is undefined.
    at ViteConfiguration.withValetCertificates (/Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/node_modules/laravel-vite/dist/index.js:136:27)
    at Object.<anonymous> (/Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/vite.config.ts:31:105)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.require.extensions.<computed> [as .ts] (/Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/node_modules/vite/dist/node/chunks/dep-24231913.js:76807:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at loadConfigFromBundledFile (/Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/node_modules/vite/dist/node/chunks/dep-24231913.js:76815:17)
    at loadConfigFromFile (/Users/jacob/Code/laravel-vite-valet-cert-arguments-bug/node_modules/vite/dist/node/chunks/dep-24231913.js:76734:32)
```

**Comment by innocenzi** [comment]
Thanks for the report -- indeed, the parameters are destructured and mutated later, which causes the issue. I'll wait for your PR or handle it myself later if you don't feel like PRing anymore. :)
