### ISSUE TITLE
Could not read configuration

### ISSUE THREAD

**Issue by fech-dev** [innocenzi/laravel-vite#198]
Hi, I've followed the docs to integrate the plugin, but when I run `yarn dev` (script in package.json that execute vite) it gives me the following error: 
```
error when starting dev server:
Error: [vite:laravel:config] Could not read configuration: Cannot read properties of undefined (reading 'undefined')
    at readConfig (/var/www/html/node_modules/vite-plugin-laravel/dist/index.js:3410:11)
    at Object.config (/var/www/html/node_modules/vite-plugin-laravel/dist/index.js:3433:26)
    at resolveConfig (/var/www/html/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:70842:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (/var/www/html/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:56354:20)
    at async CAC.<anonymous> (/var/www/html/node_modules/vite/dist/node/cli.js:688:24)
error Command failed with exit code 1.
```

I think I have found the bug in this line https://github.com/innocenzi/laravel-vite/blob/ef2401481f1140ed8c56f7e5cc03bea08c74edc7/vite-plugin-laravel/src/config.ts#L105

The regexp here seems wrong, it expects a file named vite.[someword].config.ts and if I rename the file like `vite.dev.config.ts` it works. Can be the regexp changed to not force to call the config file like the example above?

**Comment by innocenzi** [comment]
I'm off this week so I can't check, but you can force a config name by using the `config` option of the `laravel` plugin

Hope this helps in the meantime

**Comment by innocenzi** [comment]
Hey, so I'm back and I just think you don't have the right package version, make sure you have [v0.2.0-beta.5](https://github.com/innocenzi/laravel-vite/releases/tag/v0.2.0-beta.5), not [0.1.27](https://github.com/innocenzi/laravel-vite/releases/tag/0.1.27). Feel free to reopen if that was not the issue.
