### ISSUE TITLE
SyntaxError: The requested module 'crypto' does not provide an export named 'randomUUID'

### ISSUE THREAD

**Issue by akrug-va529** [innocenzi/laravel-vite#201]
I receive the following error when trying to install to a fresh install of Laravel. These are the steps I did.

composer create-project laravel/laravel vite-inertia
cd vite-inertia
npx @preset/cli apply laravel:inertia

During the install of laravel-vite I receive the following error.

file:///Users/akrug/.npm/_npx/405a1db9694bcccd/node_modules/@preset/core/dist/index.mjs:139
import { randomUUID } from "crypto";
         ^^^^^^^^^^
SyntaxError: The requested module 'crypto' does not provide an export named 'randomUUID'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

I have also tried installing laravel-vite on a fresh install of just Laravel 8 without inertia and I get the same error.

Running:
npm 8.5.0
node 14.15.0
Laravel 8

Thanks for your help.

**Comment by innocenzi** [comment]
Hi, please update your Node version to the current LTS if possible. `randomUUID` is used by the preset and comes with Node 16.7.0, you have 14.15.0.

If you can't update Node, you won't be able to use the preset, but should still be able to use Laravel Vite after installing it manually, I think.
