### ISSUE TITLE
Cannot add laravel-vite-plugin to Vite project

### ISSUE THREAD

**Issue by asiral** [innocenzi/laravel-vite#203]
Using Node version 14.8.3
Using NPM version 8.3.1

This works

```
import { defineConfig } from 'vite'
import vue from "@vitejs/plugin-vue";

export default ({ mode }) => {
	return defineConfig({
		plugins: [
			vue(),
		],
	});
};
```

This does not:

```
import { defineConfig } from 'vite'
import vue from "@vitejs/plugin-vue";
import laravel from 'vite-plugin-laravel'

export default ({ mode }) => {
	return defineConfig({
		plugins: [
			vue(),
			laravel()
		],
	});
};
```

Following the Intellisense recommendations from [Vite](https://vitejs.dev/config/#config-intellisense)

Composer includes the following entry in the `require` section: `"innocenzi/laravel-vite": "0.2.*"`

Error returned is:

TypeError: process.argv.at is not a function
    at findConfigName (/vagrant/src/laravel-8/node_modules/vite-plugin-laravel/dist/index.js:3418:35)
    at Object.config (/vagrant/src/laravel-8/node_modules/vite-plugin-laravel/dist/index.js:3427:24)
    at resolveConfig (/vagrant/src/laravel-8/node_modules/vite/dist/node/chunks/dep-f9d9421a.js:70889:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createServer (/vagrant/src/laravel-8/node_modules/vite/dist/node/chunks/dep-f9d9421a.js:56409:20)
    at async CAC.<anonymous> (/vagrant/src/laravel-8/node_modules/vite/dist/node/cli.js:688:24)

**Comment by innocenzi** [comment]
Hi, please upgrade Node to the current LTS (v16).
