### ISSUE TITLE
error during build

### ISSUE THREAD

**Issue by Aymix** [innocenzi/laravel-vite#226]
I'm using this command 'npx @preset/cli apply laravel:vite' to install laravel vite over a fresh laravel project

Having this error every time i run 'npm run dev'.

I'm not sure what i'm doing wrong please help !

error during build:
Error: [vite:laravel:config] Could not read configuration: Unexpected token W in JSON at position 1
    at readConfig (C:\wamp64\www\etudeTn\node_modules\vite-plugin-laravel\dist\index.js:3558:11)
    at Object.config (C:\wamp64\www\etudeTn\node_modules\vite-plugin-laravel\dist\index.js:3421:22)
    at resolveConfig (C:\wamp64\www\etudeTn\node_modules\vite\dist\node\chunks\dep-9c153816.js:70914:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doBuild (C:\wamp64\www\etudeTn\node_modules\vite\dist\node\chunks\dep-9c153816.js:38971:20)
    at async build (C:\wamp64\www\etudeTn\node_modules\vite\dist\node\chunks\dep-9c153816.js:38959:16)
    at async CAC.<anonymous> (C:\wamp64\www\etudeTn\node_modules\vite\dist\node\cli.js:738:9)

**Comment by innocenzi** [comment]
Can you tell me the result of `php artisan vite:config`? Also are you using a specific environment where PHP isn't directly available?
