### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by mohamad-supangat** [innocenzi/laravel-vite#275]
Laravel Framework 9.16.0
laravel-vite 0.2.0-beta.18
node v18.1.0

usage:
- update from 0.2.0-beta.11
- i use default vite.config.ts
```ts
import laravel from "vite-plugin-laravel";

const plugins = [
   vue(),
   laravel()
...
]
```
```log
failed to load config from /home/deve/projects/SekolahCRM/sekolah/vite.config.ts
error when starting dev server:
ReferenceError: navigator is not defined
    at Object.<anonymous> (/home/deve/projects/SekolahCRM/sekolah/node_modules/vite-plugin-laravel/dist/index.cjs:362:58)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/deve/projects/SekolahCRM/sekolah/vite.config.ts:30:42)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at require.extensions.<computed> [as .ts] (/home/deve/projects/SekolahCRM/sekolah/node_modules/vite/dist/node/chunks/dep-59dc6e00.j
s:61924:20)
```

**Comment by mohamad-supangat** [comment]
thanks for the fast response, i really like this package it came in laravel
