### ISSUE TITLE
RuntimeException: Unable to parse the tsconfig.json file.

### ISSUE THREAD

**Issue by anburocky3** [innocenzi/laravel-vite#286]
````sh
λ npm run dev

> dev
> vite

error when starting dev server:
Error: Command failed with exit code 1: php artisan vite:tsconfig

RuntimeException

Unable to parse the tsconfig.json file.

at S:\laragon\www\myProject\vendor\innocenzi\laravel-vite\src\Commands\UpdateTsconfigCommand.php:58
54▕     {
55▕         $raw = File::get($this->getTsConfigPath());
56▕
57▕         if (!$tsconfig = json_decode($raw, true)) {
➜  58▕             throw new \RuntimeException('Unable to parse the tsconfig.json file.');
59▕         }
60▕
61▕         $tsconfig['compilerOptions']['baseUrl'] = '.';
62▕         $tsconfig['compilerOptions']['paths'] = collect(config('vite.aliases'))

1   S:\laragon\www\myProject\vendor\innocenzi\laravel-vite\src\Commands\UpdateTsconfigCommand.php:30
Innocenzi\Vite\Commands\UpdateTsconfigCommand::writeAliases()

2   S:\laragon\www\myProject\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
Innocenzi\Vite\Commands\UpdateTsconfigCommand::handle()
at makeError (S:\laragon\www\myProject\node_modules\execa\lib\error.js:60:11)
at Function.module.exports.sync (S:\laragon\www\myProject\node_modules\execa\index.js:194:17)
at callArtisan (S:\laragon\www\myProject\node_modules\vite-plugin-laravel\dist\index.cjs:116:16)
at S:\laragon\www\myProject\node_modules\vite-plugin-laravel\dist\index.cjs:156:19
at Array.forEach (<anonymous>)
at Object.config (S:\laragon\www\myProject\node_modules\vite-plugin-laravel\dist\index.cjs:153:60)
at resolveConfig (S:\laragon\www\myProject\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:61456:33)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async createServer (S:\laragon\www\myProject\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:60080:20)
at async CAC.<anonymous> (S:\laragon\www\myProject\node_modules\vite\dist\node\cli.js:688:24)
```

**Comment by innocenzi** [comment]
I'm going to need more information. Do you currently have a `tsconfig.json`? What does `$raw` contains there?

**Comment by anburocky3** [comment]
I currently have `tsconfig.json` in my root. I made an backup and it was running after that.

But i have few queries, are you available on discord to ask questions?

**Comment by innocenzi** [comment]
You probably had a typo in it? Ping me on the Vite server in `#laravel`, I'll answer when I can 👍
