### ISSUE TITLE
Unable to Load Backend & Frontend UI

### ISSUE THREAD

**Issue by abbasmashaddy72** [innocenzi/laravel-vite#340]
Having Issue
When Running
`npm run dev --config vite.frontend.config.ts` or `npm run dev --config vite.backend.config.ts`

`Issue: (!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

Also When Running
`npm run dev:front` or `npm run dev:back`
```
failed to load config from /home/abbasmashaddy72/Documents/Sites/npc/vite.frontend.config.ts
error when starting dev server:
Error: laravel-vite-plugin: missing configuration for "input".
    at resolvePluginConfig (/home/abbasmashaddy72/Documents/Sites/npc/node_modules/laravel-vite-plugin/dist/index.js:209:15)
    at laravel (/home/abbasmashaddy72/Documents/Sites/npc/node_modules/laravel-vite-plugin/dist/index.js:27:26)
    at Object.<anonymous> (/home/abbasmashaddy72/Documents/Sites/npc/vite.frontend.config.ts:37:44)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object._require.extensions.<computed> [as .js] (file:///home/abbasmashaddy72/Documents/Sites/npc/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62851:24)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfigFromBundledFile (file:///home/abbasmashaddy72/Documents/Sites/npc/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62859:21)
```

I had done my best to find the solution by reading all the docs and searching on discussion and issues but didn't find any please help.

Config of vite.php

```[PHP]
// Backend
'backend' => [
    'entrypoints' => [
        'paths' => [
            "resources/css/backend/app.css",
            "resources/js/backend/app.ts",
        ],
        // 'ignore' => '/\\.(d\\.ts|json)$/',
    ],
    'dev_server' => [
        // 'enabled' => true,
        'url' => env('DEV_SERVER_URL', 'http://localhost:5173'),
        // 'ping_before_using_manifest' => true,
        // 'ping_url' => null,
        'ping_timeout' => 1,
        // 'key' => env('DEV_SERVER_KEY'),
        // 'cert' => env('DEV_SERVER_CERT'),
    ],
    'build_path' => 'build/backend',
],
// Frontend
'frontend' => [
    'entrypoints' => [
        'paths' => [
            "resources/css/frontend/app.scss",
            "resources/js/frontend/app.ts",
        ],
        // 'ignore' => '/\\.(d\\.ts|json)$/',
    ],
    'dev_server' => [
        // 'enabled' => true,
        'url' => env('DEV_SERVER_URL', 'http://localhost:5173'),
        // 'ping_before_using_manifest' => true,
        // 'ping_url' => null,
        'ping_timeout' => 1,
        // 'key' => env('DEV_SERVER_KEY'),
        // 'cert' => env('DEV_SERVER_CERT'),
    ],
    'build_path' => 'build/frontend',
],
```

vite.backend.config.ts

```[TS]
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import liveReload from "vite-plugin-live-reload";

export default defineConfig({
    plugins: [
        liveReload("./app/Http/**/*.php"),
        laravel({
            config: 'backend',
        }),
        {
            name: "blade",
            handleHotUpdate({ file, server }) {
                if (file.endsWith(".blade.php")) {
                    server.ws.send({
                        type: "full-reload",
                        path: "*",
                    });
                }
            },
        },
    ]
});
```

vite.frontend.config.ts
```[TS]
import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import liveReload from "vite-plugin-live-reload";

export default defineConfig({
    plugins: [
        liveReload("./app/Http/**/*.php"),
        laravel({
            config: 'frontend',
        }),
        {
            name: "blade",
            handleHotUpdate({ file, server }) {
                if (file.endsWith(".blade.php")) {
                    server.ws.send({
                        type: "full-reload",
                        path: "*",
                    });
                }
            },
        },
    ]
});
```

postcss.config.js
```[JS]
module.exports = {
    plugins: {
        autoprefixer: {},
        "postcss-advanced-variables": {},
        "postcss-import": {},
        tailwindcss: {},
        "tailwindcss/nesting": {},
    },
};
```

package.json
```[JSON]
"scripts": {
    "dev": "vite",
    "build": "vite build",
    "dev:back": "vite --config vite.backend.config.ts",
    "dev:front": "vite --config vite.frontend.config.ts",
    "build:back": "vite build --config vite.backend.config.ts",
    "build:front": "vite build --config vite.frontend.config.ts"
},
```

**Comment by abbasmashaddy72** [comment]
After Changing the Package when I run
`npm run dev:front`

Shows this error:
[vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')

@innocenzi

**Comment by innocenzi** [comment]
I think you have to remove the `config` parameter from the `laravel` plugin in both your `vite.*.config.ts`.

**Comment by abbasmashaddy72** [comment]
Same Issue

Can Please Change the Code, Show me What's Wrong

Else, You Can Access Me Git Repo to check it out:

https://github.com/abbasmashaddy72/livewire_hopital_theme

**Comment by innocenzi** [comment]
This repository [uses `laravel-vite-plugin`](https://github.com/abbasmashaddy72/livewire_hopital_theme/blob/master/package.json#L25) instead of `vite-plugin-laravel`... if you have the error you're showing, it's simply because no input file has been given.

**Comment by abbasmashaddy72** [comment]
I had added that in my local repo, but does not work

**Comment by abbasmashaddy72** [comment]
You can check my lock repo from VS Code Live Share Extension:

https://prod.liveshare.vsengsaas.visualstudio.com/join?062B337C517AED27FB514AF510C70665CB55
