### ISSUE TITLE
Error: ENOTDIR: not a directory, rmdir '/Users/abc/Repositories/xyz/webpack.mix.js'

### ISSUE THREAD

**Issue by keithbrink** [innocenzi/laravel-vite#78]
I feel like I'm missing something obvious here, but I got this error when running the apply preset:

```
[ info ]  Applying preset laravel:vite.
[ info ]  Extracting templates...
[ error ]  An error occured while applying the preset.
Error: ENOTDIR: not a directory, rmdir '/Users/abc/Repositories/xyz/webpack.mix.js'
    at Object.rmdirSync (node:fs:1158:10)
    at DeleteHandler.handle (/Users/abc/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Handlers/DeleteHandler.js:21:32)
    at PresetApplier.performActions (/Users/abc/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Applier/PresetApplier.js:78:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PresetApplier.run (/Users/abc/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Applier/PresetApplier.js:34:9)
    at async CommandLineInterface.apply (/Users/abc/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/IO/CommandLineInterface.js:57:16)
    at async CommandLineInterface.run (/Users/abc/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/IO/CommandLineInterface.js:54:16)
(node:33883) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```

I'm using node `v16.1.0` on a Mac (Big Sur). Am I doing something wrong here?

**Comment by innocenzi** [comment]
Hey, looks like an issue in [`preset`'s code](https://github.com/preset/cli/blame/main/src/Handlers/DeleteHandler.ts), not sure why I never stumbled upon this earlier. I'll investigate when I can find time, but in the meantime you can just delete the file manually and retry 👍
