### ISSUE TITLE
Can't read config file

### ISSUE THREAD

**Issue by JoeriTheGreat** [innocenzi/laravel-vite#79]
For some reason the package can't read the config file.
Don't know if this has something to do with the update to php 8.0.5 on homestead ? 

```
`Could not read configuration from PHP.
SyntaxError: Unexpected token U in JSON at position 4
    at JSON.parse (<anonymous>)
    at getConfigurationFromArtisan (/Users/dev/Code/project/node_modules/laravel-vite/dist/index.js:113:17)
    at defineConfig (/Users/dev/Code/project/node_modules/laravel-vite/dist/index.js:123:19)
    at Object.<anonymous> (/Users/dev/Code/project/node_modules/laravel-vite/dist/index.js:126:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)`
```
    
    I tried to completely remove composer and npm package, 
    reinstall and publish vite config file. Keep ketting this error.

**Comment by innocenzi** [comment]
This happens when Vite tries to call `php artisan vite:config`. Is `innocenzi/laravel-vite` properly installed? If yes, can you try monkey-patching your local NPM `laravel-vite` package to see what [this line](https://github.com/innocenzi/laravel-vite/blob/1d7a9f593b4f86fcc4dc40737ddf0c573d3754b6/npm/src/index.ts#L204) returns? You'll find it in `node_modules/laravel-vite/dist`. I think it returns `undefined` but I don't know why.

**Comment by JoeriTheGreat** [comment]
I don't know how to debug the .ts file ?  I try to add console.log() but i don't know where to look for the log ? 
I try to enter the command `php artisan vite:config` this trows an error:
array_merge(): Argument #1 must be of type array, null given

```
  at vendor/innocenzi/laravel-vite/src/Commands/ExportConfigurationCommand.php:30
     26▕             ->ltrim('/'))
     27▕             ->values();
     28▕
     29▕         return json_encode(array_merge(config('vite'), [
  ➜  30▕             'entrypoints' => $entrypoints,
     31▕         ]));
     32▕     }
     33▕ }
     34▕
```

For some reason when i log config('vite') i get null.
So my app can't find the config file in artisan command ?

**Comment by innocenzi** [comment]
> So my app can't find the config file in artisan command ?

Looks like it. Can you post your `config/vite.php` file?

**Comment by JoeriTheGreat** [comment]
This is the published vite file
```
return [
    /*
    |--------------------------------------------------------------------------
    | Entrypoints
    |--------------------------------------------------------------------------
    | The files in the configured directories will be considered
    | entry points and will not be required in the configuration file.
    | To disable the feature, set to false.
    */
    'entrypoints' => [
        'resources/assets/js/app/app.js',
    ],
    'ignore_patterns' => ["/\.d\.ts$/"],

    /*
    |--------------------------------------------------------------------------
    | Aliases
    |--------------------------------------------------------------------------
    | These aliases will be added to the Vite configuration and used
    | to generate a proper tsconfig.json file.
    */
    'aliases' => [
        '@' => 'resources/assets',
    ],

    /*
    |--------------------------------------------------------------------------
    | Static assets path
    |--------------------------------------------------------------------------
    | This option defines the directory that Vite considers as the
    | public directory. Its content will be copied to the build directory
    | at build-time.
    | https://vitejs.dev/config/#publicdir
    */
    'public_directory' => resource_path('static').'app',

    /*
    |--------------------------------------------------------------------------
    | Ping timeout
    |--------------------------------------------------------------------------
    | The maximum duration, in seconds, that the ping to the development
    | server should take while trying to determine whether to use the
    | manifest or the server in a local environment.
    */
//    'ping_timeout' => .1,
    'ping_timeout' => null,

    /*
    |--------------------------------------------------------------------------
    | Build path
    |--------------------------------------------------------------------------
    | The directory, relative to /public, in which Vite will build
    | the production files. This should match "build.outDir" in the Vite
    | configuration file.
    */
    'build_path' => 'build/app',

    /*
    |--------------------------------------------------------------------------
    | Development URL
    |--------------------------------------------------------------------------
    | The URL at which the Vite development server runs.
    | This is used to generate the script tags when developing.
    */
    'dev_url' => 'http://localhost:3000',
];
```

**Comment by innocenzi** [comment]
Can you create a repository with a minimal reproduction? I tried a fresh install and `php artisan vite:config` and `config('vite')` work properly.

**Comment by innocenzi** [comment]
Closing for inactivity, but feel free to re-open.

**Comment by fletcherhaz** [comment]
I had this issue from a manual install and, as usual, it was because Laravel's config is cached. After running
```
php artisan vendor:publish --tag=vite-config
```
to create your config file, make sure you run:
```
php artisan config:clear
```

It could be worth adding a check if the returned config object from `config('vite')` is null and then printing an error asking the user to clear their config cache. Or a note on the configuration documentation page. I imagine this is an issue that will come up again.
